# Generated by Django 4.2.23 on 2025-08-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('subadmin', 'Subadmin'), ('client', 'Client')], default='client', max_length=20)),
                ('address', models.TextField(null=True)),
                ('contact_info', models.CharField(max_length=100, null=True)),
                ('registration_number', models.CharField(max_length=50, null=True, unique=True)),
                ('tax_identification_number', models.CharField(max_length=50, null=True)),
                ('website', models.URLField(null=True)),
                ('membership_date', models.DateField(null=True)),
                ('password', models.CharField(max_length=128)),
                ('approval_status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
