# Generated by Django 4.2.23 on 2025-09-03 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testss', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('qty', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=15, null=True, unique=True)),
                ('available', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testss.category')),
            ],
        ),
    ]
