L = []
for i in range(5): L.append(i)
print(L[0])
print(L[::-1])
print(L[1::-1])
print(L[1::1])
print(L[:1:-1])
print(L[-1])
print(L[-2])
print(L[-3])
print(L[-4])
print(L[::-2])
print(L[::-3])
print(L[1:4])